version: "3"
services:



  # Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-logzio
    command: ["--config=/etc/otel-collector-config-demo.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-collector-config-demo.yaml:/etc/otel-collector-config-demo.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "55678"       # OpenCensus receiver
      - "55681:55679" # zpages extension
      - "4317:4317"   # otlp receiver

